apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb-standalone
spec:
  serviceName: database
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
        selector: database
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: database
          image: mongo:4.0.8
          ports:
            - containerPort: 27017
              name: mongodb
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: admin
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: password
      nodeSelector:
        kubernetes.io/hostname: docker-desktop
---

apiVersion: v1
kind: Service
metadata:
  name: database
  labels:
    app: database
spec:
  ports:
    - port: 27017
      name: mongodb
  clusterIP: None
  selector:
    app: database
